// Code generated by protoc-gen-go. DO NOT EDIT.
// source: KafkaMessage.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KafkaMessage_MessageType int32

const (
	KafkaMessage_TEST    KafkaMessage_MessageType = 0
	KafkaMessage_ERROR   KafkaMessage_MessageType = 1
	KafkaMessage_EVENT   KafkaMessage_MessageType = 2
	KafkaMessage_COMMAND KafkaMessage_MessageType = 3
)

var KafkaMessage_MessageType_name = map[int32]string{
	0: "TEST",
	1: "ERROR",
	2: "EVENT",
	3: "COMMAND",
}

var KafkaMessage_MessageType_value = map[string]int32{
	"TEST":    0,
	"ERROR":   1,
	"EVENT":   2,
	"COMMAND": 3,
}

func (x KafkaMessage_MessageType) String() string {
	return proto.EnumName(KafkaMessage_MessageType_name, int32(x))
}

func (KafkaMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_57cb8de32c6b88e1, []int{0, 0}
}

type KafkaMessage struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	MsgType              KafkaMessage_MessageType `protobuf:"varint,2,opt,name=MsgType,proto3,enum=KafkaMessage_MessageType" json:"MsgType,omitempty"`
	Source               string                   `protobuf:"bytes,3,opt,name=Source,proto3" json:"Source,omitempty"`
	RetryCount           int32                    `protobuf:"varint,4,opt,name=RetryCount,proto3" json:"RetryCount,omitempty"`
	Payload              string                   `protobuf:"bytes,5,opt,name=Payload,proto3" json:"Payload,omitempty"`
	DatetimeCreatedUtc   string                   `protobuf:"bytes,6,opt,name=DatetimeCreatedUtc,proto3" json:"DatetimeCreatedUtc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *KafkaMessage) Reset()         { *m = KafkaMessage{} }
func (m *KafkaMessage) String() string { return proto.CompactTextString(m) }
func (*KafkaMessage) ProtoMessage()    {}
func (*KafkaMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_57cb8de32c6b88e1, []int{0}
}

func (m *KafkaMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KafkaMessage.Unmarshal(m, b)
}
func (m *KafkaMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KafkaMessage.Marshal(b, m, deterministic)
}
func (m *KafkaMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KafkaMessage.Merge(m, src)
}
func (m *KafkaMessage) XXX_Size() int {
	return xxx_messageInfo_KafkaMessage.Size(m)
}
func (m *KafkaMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KafkaMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KafkaMessage proto.InternalMessageInfo

func (m *KafkaMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *KafkaMessage) GetMsgType() KafkaMessage_MessageType {
	if m != nil {
		return m.MsgType
	}
	return KafkaMessage_TEST
}

func (m *KafkaMessage) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *KafkaMessage) GetRetryCount() int32 {
	if m != nil {
		return m.RetryCount
	}
	return 0
}

func (m *KafkaMessage) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *KafkaMessage) GetDatetimeCreatedUtc() string {
	if m != nil {
		return m.DatetimeCreatedUtc
	}
	return ""
}

func init() {
	proto.RegisterEnum("KafkaMessage_MessageType", KafkaMessage_MessageType_name, KafkaMessage_MessageType_value)
	proto.RegisterType((*KafkaMessage)(nil), "KafkaMessage")
}

func init() {
	proto.RegisterFile("KafkaMessage.proto", fileDescriptor_57cb8de32c6b88e1)
}

var fileDescriptor_57cb8de32c6b88e1 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xf2, 0x4e, 0x4c, 0xcb,
	0x4e, 0xf4, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x9a,
	0xc8, 0xc4, 0xc5, 0x83, 0x2c, 0x2c, 0xc4, 0xc7, 0xc5, 0xe4, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8,
	0xc1, 0x19, 0xc4, 0xe4, 0x99, 0x22, 0x64, 0xcc, 0xc5, 0xee, 0x5b, 0x9c, 0x1e, 0x52, 0x59, 0x90,
	0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x67, 0x24, 0xa9, 0x87, 0x62, 0x0c, 0x94, 0x06, 0x29, 0x08,
	0x82, 0xa9, 0x14, 0x12, 0xe3, 0x62, 0x0b, 0xce, 0x2f, 0x2d, 0x4a, 0x4e, 0x95, 0x60, 0x06, 0x1b,
	0x04, 0xe5, 0x09, 0xc9, 0x71, 0x71, 0x05, 0xa5, 0x96, 0x14, 0x55, 0x3a, 0xe7, 0x97, 0xe6, 0x95,
	0x48, 0xb0, 0x28, 0x30, 0x6a, 0xb0, 0x06, 0x21, 0x89, 0x08, 0x49, 0x70, 0xb1, 0x07, 0x24, 0x56,
	0xe6, 0xe4, 0x27, 0xa6, 0x48, 0xb0, 0x82, 0x35, 0xc2, 0xb8, 0x42, 0x7a, 0x5c, 0x42, 0x2e, 0x89,
	0x25, 0xa9, 0x25, 0x99, 0xb9, 0xa9, 0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9, 0x29, 0xa1, 0x25, 0xc9,
	0x12, 0x6c, 0x60, 0x45, 0x58, 0x64, 0x94, 0xac, 0xb8, 0xb8, 0x91, 0x5c, 0x26, 0xc4, 0xc1, 0xc5,
	0x12, 0xe2, 0x1a, 0x1c, 0x22, 0xc0, 0x20, 0xc4, 0xc9, 0xc5, 0xea, 0x1a, 0x14, 0xe4, 0x1f, 0x24,
	0xc0, 0x08, 0x66, 0x86, 0xb9, 0xfa, 0x85, 0x08, 0x30, 0x09, 0x71, 0x73, 0xb1, 0x3b, 0xfb, 0xfb,
	0xfa, 0x3a, 0xfa, 0xb9, 0x08, 0x30, 0x3b, 0x71, 0x44, 0xb1, 0x81, 0x03, 0xa7, 0x38, 0x09, 0x42,
	0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x03, 0x3a, 0xeb, 0x19, 0x3a, 0x01, 0x00, 0x00,
}
